const $=id=>document.getElementById(id);
const name='glorious-waffle-x5jj6wwv7v7xc6xv4',relay=`https://${name}-8787.app.github.dev/`;
let token=localStorage.getItem('pocketGithubToken')||'',generation=0,busy=false;
$('auto').checked=localStorage.getItem('pocketAutoStart')==='1';
$('remember').checked=!!token;
const message=text=>$('notice').textContent=text;
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function github(path,method='GET'){if(!token)throw Error('请先展开首次授权，填写 GitHub 访问令牌。');const r=await fetch('https://api.github.com'+path,{method,headers:{Authorization:`Bearer ${token}`,Accept:'application/vnd.github+json'},signal:AbortSignal.timeout(20000)});if(!r.ok){let d;try{d=await r.json()}catch{}throw Error(`GitHub ${r.status}：${d?.message||'请求失败'}。请检查授权或网络。`)}return r.status===204?null:r.json()}
async function state(){const data=await github('/repos/xxby-cmd/pocket-codex-preview/codespaces?per_page=100');const cs=data.codespaces.find(c=>c.name===name);if(!cs)throw Error('没有找到配置的云端环境。');$('state').textContent=({Available:'云端运行中',Shutdown:'云端已停止',Starting:'正在启动',ShuttingDown:'正在停止'}[cs.state]||cs.state);return cs.state;}
async function ready(){try{const r=await fetch(relay+'ready',{signal:AbortSignal.timeout(5000),cache:'no-store'});const data=await r.json();return r.ok&&data.ready===true}catch{return false}}
function controls(value){busy=value;$('start').disabled=value;$('repair').disabled=value;}
async function start(){if(busy)return;const run=++generation;controls(true);try{let s=await state();if(s==='ShuttingDown'){message('等待云端停止完成……');for(let i=0;i<30&&s==='ShuttingDown';i++){await delay(3000);if(run!==generation)return;s=await state();}if(s==='ShuttingDown')throw Error('仍在停止，请稍后再启动。');}if(run!==generation)return;if(s==='Shutdown'){await github(`/user/codespaces/${name}/start`,'POST');}else if(!['Available','Starting','Provisioning','Rebuilding'].includes(s)){throw Error('云端状态为 '+s+'，请在 GitHub 查看原因。');}message('正在等待中转和端口就绪，完成后自动进入……');const deadline=Date.now()+180000;for(let i=0;i<60&&Date.now()<deadline;i++){if(run!==generation)return;if(await ready()){if(run===generation)location.replace(relay);return;}await delay(3000);}const finalState=await state();$('repair').hidden=false;throw Error(finalState==='Available'?'云端已运行，但公网中转仍不可访问。可点“重启云端修复”，无需在电脑操作；重启会中断云端连接。':'云端尚未就绪（'+finalState+'）。请稍后重试。');}catch(e){message(e.message);if(!token)$('settings').open=true;}finally{if(run===generation)controls(false)}}
$('start').onclick=start;
$('stop').onclick=async()=>{++generation;controls(true);$('stop').disabled=true;try{await github(`/user/codespaces/${name}/stop`,'POST');message('已请求停止，正在确认……');for(let i=0;i<30;i++){if(await state()==='Shutdown'){message('已停止。下次重新打开收藏入口可自动启动。');return;}await delay(3000);}message('停止结果尚未确认，请在 GitHub 查看。');}catch(e){message(e.message)}finally{$('stop').disabled=false;controls(false)}};
$('open').onclick=()=>location.assign(relay);
$('auto').onchange=()=>localStorage.setItem('pocketAutoStart',$('auto').checked?'1':'0');
$('auth').onsubmit=async e=>{e.preventDefault();token=$('token').value.trim();try{await state();localStorage.removeItem('pocketGithubToken');if($('remember').checked)localStorage.setItem('pocketGithubToken',token);$('token').value='';message('授权成功。可以启动了。');$('settings').open=false;if($('auto').checked)start();}catch(e){message(e.message)}};
$('forget').onclick=()=>{++generation;token='';localStorage.removeItem('pocketGithubToken');localStorage.removeItem('pocketAutoStart');$('auto').checked=false;$('remember').checked=false;controls(false);message('已清除这台手机的授权。');};
if(new URLSearchParams(location.search).has('stopped')){message(new URLSearchParams(location.search).get('stopped')==='unconfirmed'?'连接已中断，停止结果尚未确认；请查看云端状态或再次点停止。本次不会自动重启。':'已返回启动入口，本次不会自动重启。');history.replaceState(null,'',location.pathname);if(token)state().catch(e=>message(e.message));}else if(token&&$('auto').checked)start();else if(token)state().catch(e=>message(e.message));else $('settings').open=true;

$('repair').onclick=async()=>{if(busy)return;const run=++generation;controls(true);try{message('正在停止旧的云端连接……');await github(`/user/codespaces/${name}/stop`,'POST');let stopped=false;for(let i=0;i<40;i++){if(run!==generation)return;if(await state()==='Shutdown'){stopped=true;break;}await delay(3000);}if(!stopped)throw Error('停止尚未完成，请稍后重试。');if(run!==generation)return;controls(false);$('repair').hidden=true;await start();}catch(e){message(e.message)}finally{if(run===generation)controls(false)}};
